grid_size = [150, 150]
delta_x = 0.3

[[boundary_condition]]
condition_type = "neumann"
value = 150

[[boundary_condition]]
condition_type = "neumann"
value = 150

[[boundary_condition]]
condition_type = "neumann"
value = 0

[[boundary_condition]]
condition_type = "neumann"
value = 0